### ISSUE TITLE
EIP712 Signer doesn't work correctly

### ISSUE THREAD

**Issue by vt-btf** [Nethereum/Nethereum#634]
I get an example of EIP712 Sign from official EIPs example:
https://github.com/ethereum/EIPs/blob/b95c19f7118740cb498e0f758803037189b4ca30/assets/eip-712/Example.js
I've tested it with my private key:
https://github.com/vt-btf/EIP712-nodeJs

Then i wrote some code for Metamask with the same data and private key:
https://github.com/vt-btf/EIP712-Metamask

I had the same output of Signatures.
Then i got your test example(wich has the same data like from EIPs example):
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Signer.UnitTests/Eip712TypedDataSignerTest.cs

And created a C# project with this data:
https://github.com/vt-btf/EIP712-CSharp

MetaMask and NodeJs examples has same signature. Nethereum Signer has different signature

## Expected Behavior
All signatures are the same

## Current Behavior
MetaMask and NodeJs examples has same signature. Nethereum Signer has different signature

## Steps to Reproduce
1. https://github.com/vt-btf/EIP712-nodeJs
1. https://github.com/vt-btf/EIP712-Metamask
1. https://github.com/vt-btf/EIP712-CSharp

## Context (Environment)
Can't work with GSN v2 example

## Possible Implementation
Found out the right signature will be:
```
var key = new EthECKey(privKey);
var hashedData = Sha3Keccack.Current.CalculateHash(Eip712TypedDataSigner.Current.EncodeTypedData(typedData));
var correctSignature = key.SignAndCalculateV(hashedData);
```

**Comment by juanfranblanco** [comment]
Yes,  

This is the recovery mechanism:
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Signer.UnitTests/Eip712TypedDataSignerTest.cs#L74-L78

I will simplify it by adding it to the API :)

**Comment by vt-btf** [comment]
> Yes,
> 
> This is the recovery mechanism:
> https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Signer.UnitTests/Eip712TypedDataSignerTest.cs#L74-L78
> 
> I will simplify it by adding it to the API :)

Will you add some check for signature, like this?
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/cryptography/ECDSA.sol#L55

**Comment by juanfranblanco** [comment]
Sure i can add an extra check for the LowS but whilst this is very specific to txn malleability, and Nethereum forces it, I can see how it could be the some form of attack in scenarios like GSN that you are using for MITM.

**Comment by dustyhoppe** [comment]
Any update on this? I'm running into the same issue.

**Comment by juanfranblanco** [comment]
It is in the backlog. This will be prioritized after updating everything

**Comment by juanfranblanco** [comment]
It is in the backlog. This will be prioritized after updating everything to 1559.

**Comment by frostiq** [comment]
Guys, if you know, could you please explain what was the root cause of the issue?
In which cases it is needed to use `SignAndCalculateV` and when the regular `Sign` methods?

**Comment by tommyliu9** [comment]
Has anyone been able to resolve this signature mismatch with an alternative solution?

**Comment by jourdant** [comment]
I have been having the same issue. I've been getting a different signature between ```eth_signTypedData_v4``` from MetaMask vs ```Eip712TypedDataSigner.EncodeTypedData``` from Nethereum. I did notice that in MetaMask the ```message``` field is not set up as an array, however when setting it up, you define it as an array of ```MemberValue```.

Potentially if it is being serialised as an array (even with a single element) that could be enough for the difference in signature?

**Comment by frostiq** [comment]
@jourdant @tommyliu9, please check the "possible solution" from the first post.
In short, it seems that you just need to call a different method to calculate the signature from the data composed by `EncodeTypedData` method.

Please let me know if it works

**Comment by tommyliu9** [comment]
@frostiq Initially I tried that & it didn't work, however, I found out later that I was passing in a string into a field that should have been BigInteger for the uint256 encoding. After fixing that, the signature was valid. Hopefully, this helps someone else.

**Comment by frostiq** [comment]
I've implemented `SignTypedData` in such a way because that is what was needed for our use case (Gnosis Safe transactions). If you need to make a different signature for another use case (e.g. Metamask compatibility) – feel free to submit a PR with an alternative `SignTypedData` method if you are willing to contribute to the library. Looks like such a PR will be relatively easy to do

**Comment by tommyliu9** [comment]
Yeah sure. I'll add a method `SignTypedDataV4` that will be implementation up above ^^

**Comment by jourdant** [comment]
My use-case is slightly different, I'm not trying to sign using Nethereum, instead I'm trying to recover the signing address from an existing signature. I've basically got a REST API and I want to create an auth handler that takes a payload from a client, with a signature of that payload. To verify it, I reconstruct the TypedData at the auth handler, then verify that the recovered address matches the address in the payload. Rough code looks something like:

```
var typedData = new TypedData... //truncated for readability

var encoded = _eip712Signer.EncodeTypedData(typedData);
var resultHash = Sha3Keccack.Current.CalculateHash(encoded);
var addressRecovered = _signer.EcRecover(resultHash, signature);
```

I've got this working totally fine using libraries with node, but I'd really love to have this working with Nethereum. I've definitely confirmed that the domain, types and values match - plus I've been able to achieve it with 2 different methods in typescript. Any ideas?

**Comment by frostiq** [comment]
@jourdant, have you tried to compare the values of `encoded` and `resultHash` variables between what you get on Nethereum and TS? If they are the same, the issue is in differences in `EcRecover`. If they are different, the issue should be in the encoding part

**Comment by jourdant** [comment]
@frostiq that's a good call out. I've just done a quick comparison and the resulting hash of the typed data is different on each. So either my inputs to the typed data are not 100% matching somehow or the way the data is encoded and hashed could be different. Looks like I have more digging to do...

**Comment by frostiq** [comment]
@jourdant When I had similar issues with data encoding, it was helpful for me to get the encoded data from both sources in hex format (before hashing) and compare it byte-by-byte. That can help to localize the property where the difference is

**Comment by AlexandreBazeaud** [comment]
> My use-case is slightly different, I'm not trying to sign using Nethereum, instead I'm trying to recover the signing address from an existing signature. I've basically got a REST API and I want to create an auth handler that takes a payload from a client, with a signature of that payload. To verify it, I reconstruct the TypedData at the auth handler, then verify that the recovered address matches the address in the payload. Rough code looks something like:
> 
> ```
> var typedData = new TypedData... //truncated for readability
> 
> var encoded = _eip712Signer.EncodeTypedData(typedData);
> var resultHash = Sha3Keccack.Current.CalculateHash(encoded);
> var addressRecovered = _signer.EcRecover(resultHash, signature);
> ```
> 
> I've got this working totally fine using libraries with node, but I'd really love to have this working with Nethereum. I've definitely confirmed that the domain, types and values match - plus I've been able to achieve it with 2 different methods in typescript. Any ideas?

Having exactly the same problem, would love that have this issue resolved! Any workaround for now ?

**Comment by jourdant** [comment]
@AlexandreBazeaud did you have any luck here?

**Comment by jeffyzxc** [comment]
@AlexandreBazeaud @jourdant do u guys found a workaround for this?

**Comment by AlexandreBazeaud** [comment]
@jourdant @jeffyzxc Yup, was a my mistake, all resolved now sorry for the false alarm

**Comment by jourdant** [comment]
Any chance you could share your solution? I'd love to see how you solved it

**Comment by jeffyzxc** [comment]
Would also like to see your solution. thaanks

**Comment by juanfranblanco** [comment]
for everyone having issues (apart from arrays that is not implemented yet), post all your code.

**Comment by night-king** [comment]
Unfortunately，SignTypedDataV4 didn't solve my problem or it is incompatible with metamask(web3).
i follow author's NODEJS project: https://github.com/vt-btf/EIP712-nodeJs and host it as a API service.
our application will call this NodeJS API to generator signature.
It is my solution, hope help someone others.

**Comment by juanfranblanco** [comment]
@night-king thanks for that, i think your issue has been recovering the signature so i have added a unit test and extra methods for v4 to recover.

https://github.com/Nethereum/Nethereum/blob/master/tests/Nethereum.Signer.UnitTests/Eip712TypedDataSignerTest.cs#L18-L94

If there is any doubt that matches the signature of the example provided, and many thanks for that as it helps on matching the testing requirements in case of doubt!!

**Comment by juanfranblanco** [comment]
On the latest commit i have added support for V4 arrays and complex types using a combination of a generic definition and complex messages, hopefully this can help you. Let me know how it goes.

https://github.com/Nethereum/Nethereum/blob/ad7b4cd23adc6a478849aded47bb88833e0a2a1b/tests/Nethereum.Signer.UnitTests/Eip712TypedDataSignerSimpleScenarioTest.cs

```csharp
using System.Collections.Generic;
using Nethereum.Signer.EIP712;
using Nethereum.Util;
using Nethereum.ABI.FunctionEncoding.Attributes;
using Xunit;

namespace Nethereum.Signer.UnitTests
{
    public class Eip712TypedDataSignerSimpleScenarioTest
    {
        private readonly Eip712TypedDataSigner _signer = new Eip712TypedDataSigner();

        //Message types for easier input
        public class Mail
        {
            [Parameter("tuple", "from", 1, "Person")]
            public Person From { get; set; }

            [Parameter("tuple[]", "to", 2, "Person[]")]
            public List<Person> To { get; set; }

            [Parameter("string", "contents", 2)]
            public string Contents { get; set; }
        }

        public class Person
        {
            [Parameter("string", "name", 1)]
            public string Name { get; set; }

            [Parameter("address[]", "wallets", 2)]
            public List<string> Wallets { get; set; }
        }

        //The generic Typed schema defintion for this message
        public TypedData GetMailTypedDefintion()
        {
            return new TypedData
            {
                Domain = new Domain
                {
                    Name = "Ether Mail",
                    Version = "1",
                    ChainId = 1,
                    VerifyingContract = "0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC"
                },
                Types = new Dictionary<string, MemberDescription[]>
                {
                    ["EIP712Domain"] = new[]
                    {
                        new MemberDescription {Name = "name", Type = "string"},
                        new MemberDescription {Name = "version", Type = "string"},
                        new MemberDescription {Name = "chainId", Type = "uint256"},
                        new MemberDescription {Name = "verifyingContract", Type = "address"},
                    },
                    ["Group"] = new[]
                    {
                        new MemberDescription {Name = "name", Type = "string"},
                        new MemberDescription {Name = "members", Type = "Person[]"},

                    },
                    ["Mail"] = new[]
                    {
                        new MemberDescription {Name = "from", Type = "Person"},
                        new MemberDescription {Name = "to", Type = "Person[]"},
                        new MemberDescription {Name = "contents", Type = "string"},
                    },
                    ["Person"] = new[]
                    {
                        new MemberDescription {Name = "name", Type = "string"},
                        new MemberDescription {Name = "wallets", Type = "address[]"},
                    },
                },
                PrimaryType = "Mail",
            };
        }

        [Fact]
        private void ComplexMessageTypedDataEncodingShouldBeCorrectForV4IncludingArraysAndTypes()
        {
            var typedData = GetMailTypedDefintion();

            var mail = new Mail
            {
                From = new Person { Name = "Cow", Wallets = new List<string> { "0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826", "0xDeaDbeefdEAdbeefdEadbEEFdeadbeEFdEaDbeeF" } },
                To = new List<Person>(),
                Contents = "Hello, Bob!"
            };
            mail.To.Add(new Person { Name = "Bob", Wallets = new List<string> { "0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB", "0xB0BdaBea57B0BDABeA57b0bdABEA57b0BDabEa57", "0xB0B0b0b0b0b0B000000000000000000000000000" } });
      
            var key = new EthECKey("94e001d6adf3a3275d5dd45971c2a5f6637d3e9c51f9693f2e678f649e164fa5");
            var signature = _signer.SignTypedDataV4(mail, typedData, key);
            Assert.Equal("0x943393c998ab7e067d2875385e2218c9b3140f563694267ac9f6276a9fcc53e15c1526abe460cd6e2f570a35418f132d9733363400c44791ff7b88f0e9c91d091b", signature);
            var addressRecovered = _signer.RecoverFromSignatureV4(mail, typedData, signature);
            var address = key.GetPublicAddress();
            Assert.True(address.IsTheSameAddress(addressRecovered));

        }

    }
}

```

**Comment by juanfranblanco** [comment]
Another iteration, this makes it more simpler to define the types:

```csharp
 public class Eip712TypedDataSignerSimpleScenarioTest
    {
        private readonly Eip712TypedDataSigner _signer = new Eip712TypedDataSigner();

        //Message types for easier input
        [Struct("Mail")]
        public class Mail
        {
            [Parameter("tuple", "from", 1, "Person")]
            public Person From { get; set; }

            [Parameter("tuple[]", "to", 2, "Person[]")]
            public List<Person> To { get; set; }

            [Parameter("string", "contents", 3)]
            public string Contents { get; set; }
        }

        [Struct("Person")]
        public class Person
        {
            [Parameter("string", "name", 1)]
            public string Name { get; set; }

            [Parameter("address[]", "wallets", 2)]
            public List<string> Wallets { get; set; }
        }

        [Struct("Group")]
        public class Group
        {
            [Parameter("string", "name", 1)]
            public string Name { get; set; }

            [Parameter("tuple[]", "members", 2, "Person[]")]
            public List<Person> Members { get; set; }
        }

        //The generic EIP712 Typed schema defintion for this message
        public TypedData<Domain> GetMailTypedDefinition()
        {
            return new TypedData<Domain>
            {
                Domain = new Domain
                {
                    Name = "Ether Mail",
                    Version = "1",
                    ChainId = 1,
                    VerifyingContract = "0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC"
                },
                Types = MemberDescriptionFactory.GetTypesMemberDescription(typeof(Domain), typeof(Group), typeof(Mail), typeof(Person)),
                PrimaryType = nameof(Mail),
            };
        }

        [Fact]
        private void ComplexMessageTypedDataEncodingShouldBeCorrectForV4IncludingArraysAndTypes()
        {
            var typedData = GetMailTypedDefinition();

            var mail = new Mail
            {
                From = new Person 
                { 
                  Name = "Cow", 
                  Wallets = new List<string> { "0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826", "0xDeaDbeefdEAdbeefdEadbEEFdeadbeEFdEaDbeeF" } 
                },
                To = new List<Person>
                {
                    new Person 
                    { 
                        Name = "Bob", 
                        Wallets = new List<string> { "0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB", "0xB0BdaBea57B0BDABeA57b0bdABEA57b0BDabEa57", "0xB0B0b0b0b0b0B000000000000000000000000000" } 
                    }
                },
                Contents = "Hello, Bob!"
            };

            typedData.Domain.ChainId = 1;
            
            var key = new EthECKey("94e001d6adf3a3275d5dd45971c2a5f6637d3e9c51f9693f2e678f649e164fa5");

            var signature = _signer.SignTypedDataV4(mail, typedData, key);
            
            Assert.Equal("0x943393c998ab7e067d2875385e2218c9b3140f563694267ac9f6276a9fcc53e15c1526abe460cd6e2f570a35418f132d9733363400c44791ff7b88f0e9c91d091b", signature);
            
            var addressRecovered = _signer.RecoverFromSignatureV4(mail, typedData, signature);
            var address = key.GetPublicAddress();
            
            Assert.True(address.IsTheSameAddress(addressRecovered));

        }

    }
```

**Comment by dsalodki** [comment]
I use nuget 4.1.1 but there no SignTypedDataV4 method. Also I tried open sources and add code but cannot migrate MemberValueFactory and some other classes incompatible like Parameter and other. When are you planning update nuget?

**Comment by juanfranblanco** [comment]
I am working at the moment on the new release.

**Comment by avifeld9** [comment]
im singing an array whit "eth_signTypedData_v4" but when i try to ecrecover my signature i get the incorrect address, how should i recover a array on solidity?

**Comment by juanfranblanco** [comment]
Is this a solidity or nethereum question? @avifeld9

**Comment by juanfranblanco** [comment]
Post your schema and signature

**Comment by juanfranblanco** [comment]
Check http://playground.nethereum.com/csharp/id/1073
and this https://metamask.github.io/test-dapp/

**Comment by night-king** [comment]
Sorry, You are right.

My team finally found the key to the problem：we using Salt in Domain, so we should using  TypedData<DomainWithSalt>.
and Message property is a flat object not [].

here is our source code（Nethereum.Signer.EIP712 v4.5）:

`using Nethereum.ABI.FunctionEncoding.Attributes;
using Nethereum.Hex.HexConvertors.Extensions;
using Nethereum.Signer;
using Nethereum.Signer.EIP712;
using System;
using System.Collections.Generic;

namespace EIP712Signature
{
    class Program
    {
        private static Eip712TypedDataSigner _signer = new Eip712TypedDataSigner();
        static void Main(string[] args)
        {
            var publicKey = "0x6431dFf9ae4CF93E7C95C28e6Eb18a9a001D9ae1";
            var privateKey = "6c579bab585f186d1a5d90c401507b5068ac793e017d79be92d9fd298f01f0f1";
            var typedData = new TypedData<DomainWithSalt>
            {
                Domain = new DomainWithSalt
                {
                    Name = "BullTalk Dapp",
                    Version = "1",
                    ChainId = 4,
                    VerifyingContract = "0x7fAeFd863e979C1f52B1229B0eBd7238a142Fd45",
                    Salt = "0xf2d857f4a3edcb9b78b4d503bfe733db1e3f6cdc2b7971ee739626c97e86a558".HexToByteArray(),
                },
                Types = new Dictionary<string, MemberDescription[]>
                {
                    ["EIP712Domain"] = new[]
                    {
                        new MemberDescription {Name = "name", Type = "string"},
                        new MemberDescription {Name = "version", Type = "string"},
                        new MemberDescription {Name = "chainId", Type = "uint256"},
                        new MemberDescription {Name = "verifyingContract", Type = "address"},
                        new MemberDescription {Name = "salt", Type = "bytes32"},
                    },
                    ["Voucher"] = new[]
                    {
                        new MemberDescription {Name = "tokenAddress", Type = "address"},
                        new MemberDescription {Name = "chain", Type = "uint256"},
                        new MemberDescription {Name = "tokenID", Type = "uint256"},
                        new MemberDescription {Name = "price", Type = "uint256"},
                        new MemberDescription {Name = "amount", Type = "uint256"},
                        new MemberDescription {Name = "coinAddress", Type = "address"},
                    }
                },
                PrimaryType = "Voucher",
                Message = new[]
                {
                    new MemberValue {TypeName = "address", Value = "0x1970Ca6A5334F97D86296c6A1d0B4A6B6106e683"},
                    new MemberValue {TypeName = "uint256", Value = 4},
                    new MemberValue {TypeName = "uint256", Value = 253080146735},
                    new MemberValue {TypeName = "uint256", Value = 50},
                    new MemberValue {TypeName = "uint256", Value = 1},
                    new MemberValue {TypeName = "address", Value = "0x0000000000000000000000000000000000000000"},
                }
            };
            var signature = _signer.SignTypedDataV4(typedData, new EthECKey(privateKey));
            Console.ReadKey();
        }

    }

}
`

hope help others

**Comment by juanfranblanco** [comment]
Ah great, I understand. I included many variations of Domains, but you can create your own if you follow the same rules for the none optional values.

Here is your version in "typed" format, it can ran in the playground

```csharp

using System;
using System.Text;
using System.Collections.Generic;
using Nethereum.Signer.EIP712;
using Nethereum.Util;
using Nethereum.ABI.FunctionEncoding.Attributes;
using Nethereum.Signer;
using System.Numerics;
using Nethereum.Hex.HexConvertors.Extensions;

///EIP-712: Ethereum typed structured data hashing and signing
///This example demonstrates how to create a compatible Typed data schema definition 
/// For more information about the standard check: https://eips.ethereum.org/EIPS/eip-712
public class TypedDataSigningUsingEIP712_V4
{
	static void Main(string[] args)
	{
		var signer = new Eip712TypedDataSigner();

		//The mail typed definition, this provides the typed data schema used for this specific domain
		var typedData = GetVoucherTypedDefinition();

		//The data we are going to sign (Primary type) mail
		var voucher = new Voucher
		{
			TokenAddress = "0x1970Ca6A5334F97D86296c6A1d0B4A6B6106e683",
			Chain = 4,
			TokenId = 253080146735,
			Price = 50,
			Amount = 1,
			CoinAddress = "0x0000000000000000000000000000000000000000"
		};

		//This type data is specific to the chainId 1

		var key = new EthECKey("6c579bab585f186d1a5d90c401507b5068ac793e017d79be92d9fd298f01f0f1");
		Console.WriteLine("Signing address: " + key.GetPublicAddress());

		var signature = signer.SignTypedDataV4(voucher, typedData, key);

		Console.WriteLine("Signature: " + signature);

		var addressRecovered = signer.RecoverFromSignatureV4(voucher, typedData, signature);
		var address = key.GetPublicAddress();
		Console.WriteLine("Recovered address from signature:" + addressRecovered);
	}

	public static TypedData<DomainWithSalt> GetVoucherTypedDefinition()
	{
		return new TypedData<DomainWithSalt>
		{
			Domain = new DomainWithSalt
			{
				Name = "BullTalk Dapp",
				Version = "1",
				ChainId = 4,
				VerifyingContract = "0x7fAeFd863e979C1f52B1229B0eBd7238a142Fd45",
				Salt = "0xf2d857f4a3edcb9b78b4d503bfe733db1e3f6cdc2b7971ee739626c97e86a558".HexToByteArray(),
			},
			Types = MemberDescriptionFactory.GetTypesMemberDescription(typeof(Domain), typeof(Voucher)),
			PrimaryType = nameof(Voucher),
		};
	}

	[Struct("Voucher")]
	public class Voucher
	{
		[Parameter("address", "tokenAddress", 1)]
		public string TokenAddress { get; set; }

		[Parameter("uint256", "chain", 2)]
		public BigInteger Chain { get; set; }

		[Parameter("uint256", "tokenID", 3)]
		public BigInteger TokenId { get; set; }

		[Parameter("uint256", "price", 4)]
		public BigInteger Price { get; set; }

		[Parameter("uint256", "amount", 5)]
		public BigInteger Amount { get; set; }

		[Parameter("address", "coinAddress", 6)]
		public string CoinAddress { get; set; }
	}

}

```
